[package]
name = "cli_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
aes = "0.8"
rand = "0.8"
rpassword = "7.0"
zeroize = "1.5"
sha2 = "0.10"
anyhow = "1.0"
zerocopy = "0.7"
dirs = "5.0.1"
ring = "0.16"